"""Shell completion for the ``ntasker`` CLI (bash + zsh).

The scripts are *generated* from the argparse tree
(:func:`ntasker.cli.build_parser`), so every subcommand, option, choice
list and plugin-contributed command is covered without a hand-maintained
template. ``ntasker completion <shell>`` prints the script; ``--install``
writes it to the user-data dir and hooks it into the shell's rc file
(``~/.bashrc`` / ``~/.bash_profile`` on macOS / ``~/.zshrc``) between
marker lines, so ``--uninstall`` can remove exactly that block again.

The installed script is static; :func:`refresh_installed` rewrites it on
server startup so an upgrade (new subcommands) is picked up automatically.
"""

from __future__ import annotations

import argparse
import os
import sys
from dataclasses import dataclass, field
from pathlib import Path

import platformdirs

from ntasker.paths import APP_NAME

SHELLS = ("bash", "zsh")

_MARK_BEGIN = "# >>> ntasker completion >>>"
_MARK_END = "# <<< ntasker completion <<<"


# ---------------------------------------------------------------------------
# argparse tree -> plain data
# ---------------------------------------------------------------------------


@dataclass
class _Option:
    flags: list[str]
    help: str
    takes_value: bool
    repeatable: bool
    choices: list[str]


@dataclass
class _Positional:
    name: str
    help: str
    multiple: bool
    choices: list[str]


@dataclass
class _Node:
    """One (sub)command. ``names`` is the primary name followed by aliases."""

    names: list[str]
    help: str
    options: list[_Option] = field(default_factory=list)
    positionals: list[_Positional] = field(default_factory=list)
    children: list[_Node] = field(default_factory=list)


def _walk(parser: argparse.ArgumentParser, names: list[str], help_text: str) -> _Node:
    node = _Node(names, help_text)
    for action in parser._actions:
        if action.help is argparse.SUPPRESS:
            continue
        choices = [str(c) for c in action.choices or []]
        if isinstance(action, argparse._SubParsersAction):
            # ``choices`` maps every name (aliases included) to the parser;
            # group by parser so an alias becomes a second name, not a copy.
            helps = {ca.dest: ca.help or "" for ca in action._choices_actions}
            by_parser: dict[int, tuple[argparse.ArgumentParser, list[str]]] = {}
            for name, sub in action.choices.items():
                by_parser.setdefault(id(sub), (sub, []))[1].append(name)
            for sub, sub_names in by_parser.values():
                node.children.append(_walk(sub, sub_names, helps.get(sub_names[0], "")))
        elif action.option_strings:
            node.options.append(
                _Option(
                    list(action.option_strings),
                    action.help or "",
                    action.nargs != 0,
                    isinstance(action, argparse._AppendAction),
                    choices,
                )
            )
        else:
            node.positionals.append(
                _Positional(action.dest, action.help or "", action.nargs in ("+", "*"), choices)
            )
    return node


def _tree() -> _Node:
    from ntasker.cli import build_parser  # lazy: cli imports this module

    return _walk(build_parser(), ["ntasker"], "")


# ---------------------------------------------------------------------------
# bash
# ---------------------------------------------------------------------------

# bash 3.2 (macOS default) compatible: no associative arrays, no ``compopt``,
# no ``mapfile``. Every node is a ``case`` branch; ``-o default`` falls back
# to filename completion when nothing else matches.
_BASH_TEMPLATE = """\
# ntasker bash completion -- generated by `ntasker completion bash`.
# Load with:  eval "$(ntasker completion bash)"

_ntasker_has() {
    local x="$1" item
    shift
    for item in "$@"; do
        [ "$item" = "$x" ] && return 0
    done
    return 1
}

# Sets $subs, $opts, $valopts for the command path $1.
_ntasker_lookup() {
    subs="" opts="" valopts=""
    case "$1" in
%(lookup)s
    esac
}

# Sets $choices for option / positional $2 of the command path $1.
_ntasker_choices() {
    choices=""
    case "$1 $2" in
%(choices)s
    esac
}

_ntasker() {
    local cur prev node subs opts valopts choices i w npos
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    node="ntasker"
    npos=0
    i=1
    _ntasker_lookup "$node"
    while [ "$i" -lt "$COMP_CWORD" ]; do
        w="${COMP_WORDS[$i]}"
        if _ntasker_has "$w" $valopts; then
            i=$((i + 2))
            continue
        fi
        case "$w" in
            -*) i=$((i + 1)); continue ;;
        esac
        if [ -n "$subs" ] && _ntasker_has "$w" $subs; then
            node="${node}_${w//-/_}"
            npos=0
            _ntasker_lookup "$node"
        else
            npos=$((npos + 1))
        fi
        i=$((i + 1))
    done
    if _ntasker_has "$prev" $valopts; then
        _ntasker_choices "$node" "$prev"
        COMPREPLY=( $(compgen -W "$choices" -- "$cur") )
        return
    fi
    case "$cur" in
        -*) COMPREPLY=( $(compgen -W "$opts" -- "$cur") ); return ;;
    esac
    if [ -n "$subs" ]; then
        COMPREPLY=( $(compgen -W "$subs" -- "$cur") )
    else
        _ntasker_choices "$node" "@$npos"
        COMPREPLY=( $(compgen -W "$choices" -- "$cur") )
    fi
}

complete -o default -F _ntasker ntasker
"""


def _bash_paths(node: _Node, prefixes: list[str]) -> list[str]:
    """Every ``case`` pattern for ``node``: prefixes x its names, ``-`` -> ``_``."""
    return [f"{p}_{n}".replace("-", "_") for p in prefixes for n in node.names]


def _render_bash(root: _Node) -> str:
    lookup: list[str] = []
    choices: list[str] = []

    def emit(node: _Node, paths: list[str]) -> None:
        subs = " ".join(n for c in node.children for n in c.names)
        opts = " ".join(f for o in node.options for f in o.flags)
        valopts = " ".join(f for o in node.options if o.takes_value for f in o.flags)
        pattern = "|".join(paths)
        lookup.append(
            f"        {pattern})\n"
            f'            subs="{subs}"\n'
            f'            opts="{opts}"\n'
            f'            valopts="{valopts}"\n'
            f"            ;;"
        )
        for opt in node.options:
            if opt.choices:
                for flag in opt.flags:
                    pat = "|".join(f'"{p} {flag}"' for p in paths)
                    choices.append(f'        {pat}) choices="{" ".join(opt.choices)}" ;;')
        for idx, pos in enumerate(node.positionals):
            if pos.choices:
                pat = "|".join(f'"{p} @{idx}"' for p in paths)
                choices.append(f'        {pat}) choices="{" ".join(pos.choices)}" ;;')
        for child in node.children:
            emit(child, _bash_paths(child, paths))

    emit(root, ["ntasker"])
    return _BASH_TEMPLATE % {"lookup": "\n".join(lookup), "choices": "\n".join(choices)}


# ---------------------------------------------------------------------------
# zsh
# ---------------------------------------------------------------------------

_ZSH_HEADER = """\
#compdef ntasker
# ntasker zsh completion -- generated by `ntasker completion zsh`.
# Load with:  eval "$(ntasker completion zsh)"
# or save as `_ntasker` into a directory on $fpath.
"""

_ZSH_FOOTER = """\
if [ "$funcstack[1]" = "_ntasker" ]; then
    _ntasker "$@"
else
    (( $+functions[compdef] )) || { autoload -Uz compinit && compinit; }
    compdef _ntasker ntasker
fi
"""


def _zq(text: str) -> str:
    """Escape ``text`` for use inside a single-quoted ``_arguments`` spec."""
    return _zd(text).replace("[", "\\[").replace("]", "\\]")


def _zd(text: str) -> str:
    """Escape ``text`` for a single-quoted ``_describe`` entry (``name:help``)."""
    return text.replace("'", "'\\''").replace(":", "\\:")


def _zsh_func(node: _Node, path: list[str]) -> str:
    fname = "_ntasker_cmd_" + "_".join(path).replace("-", "_")
    specs: list[str] = []
    for opt in node.options:
        # Repeatable options take a ``*`` prefix; short/long twins exclude each other.
        prefix = "*" if opt.repeatable else f"({' '.join(opt.flags)})" if len(opt.flags) > 1 else ""
        for flag in opt.flags:
            spec = f"{prefix}{flag}[{_zq(opt.help)}]"
            if opt.takes_value:
                name = flag.lstrip("-")
                spec += f":{name}:" + (f"({' '.join(opt.choices)})" if opt.choices else "_files")
            specs.append(spec)
    for idx, pos in enumerate(node.positionals, start=1):
        spec = f"{'*' if pos.multiple else idx}:{_zq(pos.name)}:"
        if pos.choices:
            spec += f"({' '.join(pos.choices)})"
        specs.append(spec)
    body = [f"{fname}() {{"]
    if node.children:
        body.append("    local -a subcmds")
        body.append("    subcmds=(")
        for child in node.children:
            for name in child.names:
                body.append(f"        '{name}:{_zd(child.help)}'")
        body.append("    )")
        specs.append(f'{len(node.positionals) + 1}: :{{_describe "command" subcmds}}')
        specs.append("*:: :->args")
    body.append("    _arguments -C \\")
    body.extend(f"        '{s}' \\" for s in specs)
    body[-1] = body[-1][:-2]  # drop the trailing continuation
    if node.children:
        body.append("    case $state in")
        body.append("        args)")
        body.append("            case $line[1] in")
        for child in node.children:
            child_fn = "_ntasker_cmd_" + "_".join([*path, child.names[0]]).replace("-", "_")
            body.append(f"                {'|'.join(child.names)}) {child_fn} ;;")
        body.append("            esac")
        body.append("            ;;")
        body.append("    esac")
    body.append("}")
    out = ["\n".join(body)]
    for child in node.children:
        out.append(_zsh_func(child, [*path, child.names[0]]))
    return "\n\n".join(out)


def _render_zsh(root: _Node) -> str:
    funcs = _zsh_func(root, ["ntasker"])
    return f'{_ZSH_HEADER}\n{funcs}\n\n_ntasker() {{ _ntasker_cmd_ntasker "$@"; }}\n\n{_ZSH_FOOTER}'


# ---------------------------------------------------------------------------
# public API
# ---------------------------------------------------------------------------


def render(shell: str) -> str:
    """Return the completion script for ``shell`` (``bash`` or ``zsh``)."""
    if shell not in SHELLS:
        raise ValueError(f"unsupported shell: {shell}")
    root = _tree()
    return _render_bash(root) if shell == "bash" else _render_zsh(root)


def script_path(shell: str) -> Path:
    """Where ``--install`` writes the script: ``<user-data>/completions/ntasker.<shell>``."""
    return Path(platformdirs.user_data_dir(APP_NAME)) / "completions" / f"ntasker.{shell}"


def rc_path(shell: str) -> Path:
    """The shell's startup file the source line goes into.

    macOS Terminal opens *login* bash shells, which read ``~/.bash_profile``
    and skip ``~/.bashrc``. zsh honours ``$ZDOTDIR``.
    """
    if shell == "zsh":
        return Path(os.environ.get("ZDOTDIR") or Path.home()) / ".zshrc"
    return Path.home() / (".bash_profile" if sys.platform == "darwin" else ".bashrc")


def _rc_block(shell: str) -> str:
    return (
        f'{_MARK_BEGIN}\n[ -f "{script_path(shell)}" ] && . "{script_path(shell)}"\n{_MARK_END}\n'
    )


def _strip_block(text: str) -> str:
    start = text.find(_MARK_BEGIN)
    end = text.find(_MARK_END)
    if start < 0 or end < 0:
        return text
    end = text.find("\n", end) + 1 or len(text)
    rest = (text[:start] + text[end:]).rstrip("\n")
    return rest + "\n" if rest else ""


def is_installed(shell: str) -> bool:
    rc = rc_path(shell)
    return script_path(shell).exists() and rc.exists() and _MARK_BEGIN in rc.read_text()


def install(shell: str) -> Path:
    """Write the script and hook it into the rc file. Idempotent; returns the rc path."""
    script = script_path(shell)
    script.parent.mkdir(parents=True, exist_ok=True)
    script.write_text(render(shell))
    rc = rc_path(shell)
    text = rc.read_text() if rc.exists() else ""
    if _MARK_BEGIN not in text:
        if text and not text.endswith("\n"):
            text += "\n"
        rc.write_text(text + ("\n" if text else "") + _rc_block(shell))
    return rc


def uninstall(shell: str) -> bool:
    """Remove the rc block and the script. Returns whether anything was removed."""
    removed = False
    rc = rc_path(shell)
    if rc.exists():
        text = rc.read_text()
        if _MARK_BEGIN in text:
            rc.write_text(_strip_block(text))
            removed = True
    script = script_path(shell)
    if script.exists():
        script.unlink()
        removed = True
    return removed


def refresh_installed() -> None:
    """Regenerate every installed script (server startup: picks up new subcommands)."""
    for shell in SHELLS:
        if script_path(shell).exists():
            script_path(shell).write_text(render(shell))


def status() -> dict[str, dict]:
    """Per-shell install state; ``rc`` is shown to the user, so ``~``-abbreviated."""
    home = str(Path.home())
    return {
        shell: {
            "installed": is_installed(shell),
            "rc": str(rc_path(shell)).replace(home, "~", 1),
        }
        for shell in SHELLS
    }
